const data = [

    {
        id : 1,
        url : '1.jpg',
        name : 'Nokia v10',
        brand: 'Nokia',
        price: 5000000,
    },
    {
        id : 2,
        url : '2.jpg',
        name : 'iphone 5s',
        brand: 'Apple',
        price: 5555000,
    },
    {
        id : 3,
        url : '3.jpg',
        name : 'xiaomi mi 11 t pro',
        brand: 'xiaomi',
        price: 58756000,
    },
    {
        id : 4,
        url : '4.jpg',
        name : 'samsung s20 FE',
        brand: 'Samsung',
        price: 345000,
    },
    {
        id : 5,
        url : '5.jpg',
        name : 'xiaomi 14 pro',
        brand: 'Xiaomi',
        price: 7000,
    },
    {
        id : 6,
        url : '6.jpg',
        name : 'iphone x',
        brand: 'Apple',
        price: 67000,
    },
    {
        id : 7,
        url : '7.jpg',
        name : 'S24 ultra',
        brand: 'Samsung',
        price: 67898000,
    },
    {
        id : 8,
        url : '8.jpg',
        name : 'p50 pro',
        brand: 'Huawi',
        price: 67445645000,
    },
    {
        id : 9,
        url : '9.jpg',
        name : 'Z-Fold',
        brand: 'Samsung',
        price: 670121500,
    },
    {
        id : 10,
        url : '10.jpg',
        name : 'Dodge S89 pro',
        brand: 'Dodge',
        price: 67070000,
    },
    {
        id : 11,
        url : '11.jpg',
        name : 'iphone s5',
        brand: 'Apple',
        price: 6340000000,
    },
    {
        id : 12,
        url : '12.jpg',
        name : 'grand prime plus',
        brand: 'Samsung',
        price: 4540000,
    },
    {
        id : 13,
        url : '13.jpg',
        name : 'S98 pro',
        brand: 'Dodge',
        price: 4543340000,
    },
    {
        id : 14,
        url : '14.jpg',
        name : 'nokia v2',
        brand: 'nokia',
        price: 99000000,
    },
    {
        id : 15,
        url : '15.jpg',
        name : 'xiaomi f3',
        brand: 'Xiaomi',
        price: 15000000,
    },
]

export default data;